### ISSUE TITLE
Questions regarding the examples/code

### ISSUE THREAD

**Issue by DanielNaro** [CaiLiLab/MuRaL#3]
Hi,
I have some questions regarding the examples/code ?
- In the example [training bed](https://github.com/CaiLiLab/MuRaL/blob/c3b666bc12750a3e48de242ab6cc231f62675a39/examples/data/training.sorted.bed), why does the fourth column have sometimes numerical values? It seems to correspond with when there is a mutation.
- I am not sure if there is a place where the fourth column is used in the code. Is there one?
- line https://github.com/CaiLiLab/MuRaL/blob/15860dda6eae0869483284ff97a88d993eab7d24/MuRaL/preprocessing.py#L496 sets 'N's to 'A's. Is it not an issue for those datasets which have C/G in the position of interest?
Regards,
Daniel

**Comment by cailigd** [comment]
Hi Daniel,

Thanks for questions! 

Regarding your 1st and 2nd points, the fourth column of bed files is never used in the code so the content would not matter. The numerical values can be ignored. Sorry for the confusion and we will update the example files/docs in later versions. 

Regarding the 3rd point, 'N's here can occur only in the flanking regions of a focal site of interest. When preparing the input BED file, the focal sites (middle positions) need to be one of A/T or C/G, otherwise it will cause errors when running the code. Setting 'N's to 'A's is indeed a compromise, but this happens rarely for most genomes. One can also remove the sites with 'N's in flanking regions for training/prediction.

BTW, thanks for spotting the typo in 'prepare_dataset_np'.

Cai
