### ISSUE TITLE
Some abnormal about   calc_kmer_corr

### ISSUE THREAD

**Issue by bighawkin** [CaiLiLab/MuRaL#9]
I use mural_predict to predict per site mutation rate of one chromosome site，and  then use calc_kmer_corr to calculate correlation coefficient between observed and predicted  mutation rate. But I find some strange  result. 
![图片](https://github.com/CaiLiLab/MuRaL/assets/88721330/3866f75d-f2e0-498f-a0b1-a85881ef37fe)

 
![图片](https://github.com/CaiLiLab/MuRaL/assets/88721330/6d06bcce-1630-439c-9608-4bac4247dc83)

There are additional lines, I'm not sure if it's normal. But from my observation, this leads to a lower calculated correlation coefficient, some even becoming negative (when I remove the extra rows, the correlation coefficient I calculated myself becomes positive)

I'm not sure what to do,  hope to receive your reply. Thank you very much！！

**Comment by bighawkin** [comment]
![图片](https://github.com/CaiLiLab/MuRaL/assets/88721330/cd154583-8e90-4660-bb04-753c64bd8227)
some other  supplements. 5mer and 7mer also have similar question.

**Comment by cailigd** [comment]
Thanks for reporting the issue!

I guess this is probably due to incorrect k-mer counts at the very ends of the chromosomes. 

There are two ways to resolve this:
1. The estimated mutaiton rates for nucleotide positions at the very beginnig or end of a sequence are not very accurate because some flanking nucleotides are not availalbe. For example, for the 1st nucleotide of a chromosome, the flanking nucleotides on the left side are not available. Before we dropped the first/last 10 nucleotides of a chromosome when doing prediction. So to resove the problem, you can remove a few sites at the both ends of each chromosome in your prediction file(s) before running calc_kmer_corr.

2. The second solution is to modify the Line 140 in "MuRal/bin/calc_kmer_corr" file and re-install the package (we will release an updated version in near future to fix this):
change the Line 140:
   **kmer_calculate(base, seq, mut_type, prob1, prob2, prob3, all_kmers, pred_prob1_sum, pred_prob2_sum, pred_prob3_sum, mut1_sum, mut2_sum, mut3_sum)**
to:
  **if len(seq) == kmer_length:
      kmer_calculate(base, seq, mut_type, prob1, prob2, prob3, all_kmers, pred_prob1_sum, pred_prob2_sum, pred_prob3_sum, mut1_sum, mut2_sum, mut3_sum)**

**Comment by bighawkin** [comment]
Sincerely thank you for your prompt reply！
